mypyquiz/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from quiz import views

urlpatterns = [
    path('quiz/', include('quiz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

quiz/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'quiz'
urlpatterns = [
    # basic pages
    path('', views.IndexView.as_view(), name='index'),
    path('subjects/', views.SubjectsView.as_view(), name='all_subjects'),
    path('quizzes/', views.QuizzesView.as_view(), name='all_quizzes'),
    path('subjects/<int:pk>/', views.SubjQuizzesView.as_view(), name='subj_quizzes'),

    # taking a quiz
    path('subjects/<int:subject_id>/<int:pk>/', views.QuizDetailView.as_view(), name='quiz_detail'),
    path('<int:subject_id>/<int:pk>/start/', views.StartQuizView.as_view(), name='start_quiz'),
    path('<int:quiz_id>/submit/', views.submit_quiz, name='submit'),

    # user profile
    path('profile/<int:user_id>/', views.profile, name='profile'),
    re_path(r'^profile/(?P<username>[\w\d_.@+-]+)/$', views.profile, name='profile'),
    path('profile/<int:user_id>/all_results/', views.all_user_results, name='all_user_results'),

    # editing quizzes
    path('quizzes/create/', views.new_quiz, name='new_quiz'),
    path('quizzes/created', views.quiz_created, name='quiz_created'),
    path('quizzes/<int:quiz_id>/delete/', views.delete_quiz, name='delete_quiz'),

    # editing subjects
    path('subjects/create/', views.new_subject, name='new_subject'),
    path('subjects/created/', views.subject_created, name='subject_created'),
    path('subjects/<int:subject_id>/delete/', views.delete_subject, name='delete_subject'),

    # viewing results
    path('results/', views.view_results, name='all_results'),
    path('results/quizzes/<int:quiz_id>/', views.view_results, name='results_by_quiz'),
    path('results/users/<int:user_id>/', views.view_results, name='results_by_user'),
    path('results/subjects/<int:subject_id>/', views.view_results, name='results_by_subject'),
    path('results/<int:result_id>', views.result_details, name='result_details'),
    path('ajax/results/subjects/<int:subject_id>/', views.get_results_table_data, name='ajax_results_by_subj'),
    path('ajax/results/users/<int:user_id>/', views.get_results_table_data, name='ajax_results_by_user'),
    path('ajax/results/quizzes/<int:quiz_id>/', views.get_results_table_data, name='ajax_results_by_quiz'),
    path('ajax/results/', views.get_results_table_data, name='ajax_all_results'),

    # signup and password reset
    path('signup/', views.signup, name='signup'),
    re_path(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    re_path(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            auth_views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

]

quiz/forms.py
from django import forms
from .models import Quiz, Question, Option
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from datetime import datetime


class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ('subject', 'quiz_name', 'difficulty', 'description')
        widgets = {
            'description': forms.Textarea(attrs={'cols': 45, 'rows': 3}),
        }
        labels = {
            'subject': 'Choose quiz subject',
            'quiz_name': 'Enter quiz name',
            'description': 'Enter quiz description',
            'difficulty': 'Choose quiz difficulty'
        }

    def save(self, commit=True):
        quiz = super(QuizForm, self).save(commit=False)
        quiz.pub_date = datetime.now()
        if commit:
            quiz.save()
        return quiz


class SubjForm(forms.Form):
    subj_name = forms.CharField(label='Enter subject name')


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('question_type', 'question_text')
        widgets = {
            'question_text': forms.Textarea(attrs={'cols': 45, 'rows': 3}),
        }
        labels = {
            'question_type': 'Question type',
            'question_text': 'Question text'
        }


OptionFormset = inlineformset_factory(Question,
                                      Option,
                                      exclude=['question'],
                                      widgets={
                                          'explanation': forms.Textarea(attrs={'rows': 3, 'cols': 45})
                                      },
                                      extra=0)


class BaseQuestionsFormset(BaseInlineFormSet):
    def add_fields(self, form, index):
        super(BaseQuestionsFormset, self).add_fields(form, index)
        form.nested = OptionFormset(
                        instance=form.instance,
                        data=form.data if form.is_bound else None,
                        files=form.files if form.is_bound else None,
                        prefix='option-%s-%s' % (
                            form.prefix,
                            OptionFormset.get_default_prefix()))

    def is_valid(self):
        result = super(BaseQuestionsFormset, self).is_valid()
        if self.is_bound:
            for form in self.forms:
                if hasattr(form, 'nested'):
                    result = result and form.nested.is_valid()
        return result

    def save(self, commit=True):
        result = super(BaseQuestionsFormset, self).save(commit=commit)
        for form in self.forms:
            if hasattr(form, 'nested'):
                if not self._should_delete_form(form):
                    form.nested.save(commit=commit)
        return result


QuestionsFormset = inlineformset_factory(Quiz,
                                         Question,
                                         exclude=['quiz'],
                                         formset=BaseQuestionsFormset,
                                         widgets={
                                             'question_text': forms.Textarea(attrs={'rows': 3, 'cols': 45})
                                         },
                                         extra=0)


class BaseQuizFormset(BaseInlineFormSet):
    def add_fields(self, form, index):
        super(BaseQuizFormset, self).add_fields(form, index)
        form.nested = QuestionsFormset(
                        instance=form.instance,
                        data=form.data if form.is_bound else None,
                        files=form.files if form.is_bound else None,
                        prefix='question-%s-%s' % (
                            form.prefix,
                            QuestionsFormset.get_default_prefix()))

    def is_valid(self):
        result = super(BaseQuizFormset, self).is_valid()
        if self.is_bound:
            for form in self.forms:
                if hasattr(form, 'nested'):
                    result = result and form.nested.is_valid()
        return result

    def save(self, commit=True):
        result = super(BaseQuizFormset, self).save(commit=commit)
        for form in self.forms:
            if hasattr(form, 'nested'):
                if not self._should_delete_form(form):
                    form.nested.save(commit=commit)
        return result

quiz/views.py
from collections import defaultdict
from django.shortcuts import get_object_or_404, render, redirect
from .models import Subject, Quiz, Question, Option, UserResult
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from .forms import QuizForm, SubjForm
from django.contrib.auth.decorators import login_required, user_passes_test
import json


# displays 5 newest quizzes
class IndexView(generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'latest_quizzes_list'

    def get_queryset(self):
        return Quiz.objects.order_by('-pub_date')[:5]


# displays a list of all subjects
class SubjectsView(generic.ListView):
    template_name = 'quiz/all_subjects.html'
    context_object_name = 'subjects'

    def get_queryset(self):
        return Subject.objects.all()


# displays a list of all quizzes
class QuizzesView(generic.ListView):
    model = Quiz
    template_name = 'quiz/all_quizzes.html'
    context_object_name = 'quizzes'


# displays all quizzes on given subject
class SubjQuizzesView(generic.ListView):
    template_name = 'quiz/subject_quizzes.html'
    context_object_name = 'quizzes'

    def get_queryset(self):
        subject_id = self.kwargs['pk']
        return Quiz.objects.filter(subject=subject_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subject'] = Subject.objects.get(pk=self.kwargs['pk'])
        return context


class QuizDetailView(generic.DetailView):
    model = Quiz
    template_name = 'quiz/detail.html'


class StartQuizView(LoginRequiredMixin, generic.DetailView):
    model = Quiz
    template_name = 'quiz/start_quiz.html'


def submit_quiz(request, quiz_id):
    current_user = request.user
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    try:
        user_answers = {}
        answers_json = defaultdict(dict)
        current_score = 0
        questions = quiz.question_set.all()
        for question in questions:
            if question.question_type == 'RB':
                selected_option = question.option_set.get(pk=request.POST['question{}'.format(question.id)])
                user_answers[question] = selected_option
                answers_json[question.question_text][selected_option.option_text] = selected_option.correct_option
                if selected_option.correct_option:
                    current_score += 1
            elif question.question_type == 'CB':
                selected_options = question.option_set.filter(
                    pk__in=request.POST.getlist('question{}'.format(question.id)))
                correct_options = question.option_set.filter(correct_option=True)
                user_answers[question] = selected_options
                for sel_option in selected_options:
                    answers_json[question.question_text][sel_option.option_text] = sel_option.correct_option
                if len(selected_options) == len(correct_options) and all(
                        [opt.correct_option for opt in selected_options]):
                    current_score += 1
            elif question.question_type == 'TXT':
                selected_option = request.POST['question{}'.format(question.id)]
                correct_options = question.option_set.filter(correct_option=True)
                if selected_option.strip().lower() in map(lambda s: s.option_text.strip().lower(), correct_options):
                    current_score += 1
                    answers_json[question.question_text][selected_option] = True
                    user_answers[question] = [selected_option, True, correct_options[0]]
                else:
                    answers_json[question.question_text][selected_option] = False
                    user_answers[question] = [selected_option, False, correct_options[0]]
        answers_json = json.dumps(answers_json)
        new_result = UserResult(user=current_user,
                                quiz=quiz,
                                score=current_score,
                                date_taken=datetime.now(),
                                answers=answers_json)
        new_result.save()
    except (KeyError, Option.DoesNotExist):
        return render(request, 'quiz/start_quiz.html', {
            'quiz': quiz,
            'error_message': 'You didn\'t select an answer'
        })
    else:
        return render(request, 'quiz/submit_quiz.html', {'result': new_result,
                                                         'user_answers': user_answers,
                                                         'answers_json': answers_json,
                                                         })


def profile(request, user_id=None, username=None):
    if user_id:
        user = get_object_or_404(User, pk=user_id)
    elif username:
        user = get_object_or_404(User, username=username)
    all_user_results = UserResult.objects.filter(user=user)
    if all_user_results:
        latest_user_results = all_user_results.order_by('-date_taken')[:5]
        ordered_by_score_percent = sorted(all_user_results,
                                          key=lambda r: int(r.calc_score_percent()[:-1]),
                                          reverse=True)[:5]
        best_user_results = ordered_by_score_percent
        return render(request, 'quiz/profile.html', {'profile_user': user,
                                                     'has_results': True,
                                                     'latest_user_results': latest_user_results,
                                                     'best_user_results': best_user_results})
    else:
        return render(request, 'quiz/profile.html', {'profile_user': user,
                                                     'has_results': False})


def all_user_results(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    all_user_results = UserResult.objects.filter(user=user)
    return render(request, 'quiz/all_user_results.html', {'profile_user': user,
                                                          'results': all_user_results})


def can_create(user):
    return user.is_superuser


@user_passes_test(can_create)
def new_quiz(request):
    quiz_form = QuizForm()
    return render(request, 'quiz/new_quiz.html', {'quiz_form': quiz_form})


def quiz_created(request):
    if request.method == 'POST':
        hidden_input = request.POST['quiz_json']
        quiz_form = QuizForm(request.POST)
        if quiz_form.is_valid():
            quiz_form.save()
            questions_json = json.loads(hidden_input)
            for question in [questions_json[q] for q in questions_json]:
                if question['question_type'] == 'radioQuestion':
                    quesType = 'RB'
                elif question['question_type'] == 'checkboxQuestion':
                    quesType = 'CB'
                elif question['question_type'] == 'textQuestion':
                    quesType = 'TXT'
                quesText = question['question_text']
                new_ques = Question(quiz=quiz_form.instance,
                                    question_type=quesType,
                                    question_text=quesText)
                new_ques.save()
                options = question['options']
                for option in options:
                    new_option = Option(question=new_ques,
                                        option_text=option,
                                        correct_option=options[option])
                    new_option.save()
        return render(request, 'quiz/quiz_created.html', {'quiz_name': quiz_form.instance.quiz_name})


def delete_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, id=quiz_id)
    quiz_name = quiz.quiz_name
    quiz.delete()
    return render(request, 'quiz/delete_quiz.html', {'quiz_name': quiz_name})


@user_passes_test(can_create)
def new_subject(request):
    subj_form = SubjForm()
    return render(request, 'quiz/new_subject.html', {'subj_form': subj_form})


def subject_created(request):
    if request.method == 'POST':
        subj_form = SubjForm(request.POST)
        if subj_form.is_valid():
            subj_name = request.POST['subj_name']
            new_subj = Subject(subj_name=subj_name)
            new_subj.save()
        return render(request, 'quiz/subject_created.html', {'subj_name': subj_name})


def delete_subject(request, subject_id):
    subject = get_object_or_404(Subject, id=subject_id)
    subj_name = subject.subj_name
    subject.delete()
    return render(request, 'quiz/delete_subject.html', {'subj_name': subj_name})


@login_required(login_url='/accounts/login/')
def view_results(request, quiz_id=None, user_id=None, subject_id=None):
    cur_user = request.user
    results_type = 'all'
    results_filter = 'none'
    results_set = UserResult.objects.all()
    if quiz_id:
        results_type = 'by_quiz'
        results_filter = str(Quiz.objects.get(pk=quiz_id))
        results_set = results_set.filter(quiz_id=quiz_id)
    if subject_id:
        results_type = 'by_subj'
        results_filter = str(Subject.objects.get(pk=subject_id))
        results_set = results_set.filter(quiz__subject__pk=subject_id)
    if user_id:
        results_type = 'by_user'
        results_filter = str(User.objects.get(pk=user_id))
        results_set = results_set.filter(user_id=user_id)
    if not cur_user.userrole.isSupervisor and not cur_user.is_superuser:
        results_set = results_set.filter(user_id=cur_user.id)
    all_subjects = Subject.objects.all()
    all_quizzes = Quiz.objects.all()
    all_users = User.objects.all()
    return render(request,
                  'quiz/results.html',
                  {
                      'results_type': results_type,

quiz/templates/quiz/all_user_results.html
{% extends "base_generic.html" %}
{% block title %}<title>{{ profile_user.get_username }} Results | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h1><span class="glyphicon glyphicon-user"></span> {{ profile_user.get_username }} </h1>
    <a href="{% url 'quiz:profile' username=profile_user.get_username %}"><span class="glyphicon glyphicon-arrow-left"></span> Back to user's profile</a>
    {% if user.is_authenticated and user.id == profile_user.id or user.is_staff %}
        {% if results %}
        <div class="table-responsive">
            <table class="table table-striped" id="allUserResultsTable">
                <thead>
                    <tr class="header">
                        <th width="35%">Quiz</th>
                        <th width="25%">Score</th>
                        <th width="40%">Date</th>
                    </tr>
                </thead>
                {% for line in results %}
                <tr>
                    <td>{{ line.quiz }}</td>
                    <td>{{ line.score }}</td>
                    <td>{{ line.date_taken }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div id="nav-wrapper">
            <div id="select-page-size">
                <label for="items-on-page">Lines on page</label>
                <select name="items-on-page" id="items-on-page" onchange="paginateTableByItemsLimit('allUserResultsTable')">
                    <option>10</option>
                    <option selected="selected">20</option>
                    <option>40</option>
                </select>
            </div>
        </div>
        {% else %}
            <p>No results to show yet!</p>
        {% endif %}
    {% else %}
        <p>you can't see this user's info</p>
    {% endif %}
{% endblock %}
{% block script %}
<script>
var selectBox = document.getElementsByName("items-on-page")[0];
$('#allUserResultsTable').paginate({ limit: selectBox.options[selectBox.selectedIndex].value,
                                     optional: false,
                                     navigationWrapper: $("#nav-wrapper") });
</script>
{% endblock %}

quiz/templates/quiz/delete_quiz.html
{% extends "base_generic.html" %}
{% block title %}<title>Quiz deleted | MyPyQuiz</title>{% endblock %}
{% block content %}
<h2>Quiz {{quiz_name}} deleted!</h2>
<p><a href="{% url 'quiz:all_quizzes' %}">Go back to all quizzes</a></p>
{% endblock %}

quiz/templates/quiz/delete_subject.html
{% extends "base_generic.html" %}
{% block title %}<title>Subject deleted | MyPyQuiz</title>{% endblock %}
{% block content %}
<h2>Subject {{ subj_name }} deleted!</h2>
<p><a href="{% url 'quiz:all_subjects' %}">Go back to all subjects</a></p>
{% endblock %}

quiz/templates/quiz/detail.html
{% extends "base_generic.html" %}
{% block title %}<title>{{ quiz }} | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h1>{{ quiz }}</h1>
    <div>Subject: {{ quiz.subject }}</div>
    <div>Difficulty: {{ quiz.difficulty }}</div>
    <div>Description: {{ quiz.description }}</div>
    <br>
    <p><a href="{% url 'quiz:start_quiz' subject_id=quiz.subject_id pk=quiz.id %}">
            <strong><span class="glyphicon glyphicon-check"></span>&nbsp;&nbsp; Start quiz!</strong>
        </a>
    </p>
    {% if user.is_authenticated and user.is_staff %}
    <p>
        <a href="{% url 'quiz:delete_quiz' quiz_id=quiz.id %}">
            <span class="glyphicon glyphicon-trash"></span>&nbsp;&nbsp; Delete quiz
        </a>
    </p>
    {% endif %}
{% endblock %}

quiz/templates/quiz/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Latest quizzes | MyPyQuiz</title>
</head>
<body>
{% extends "base_generic.html" %}

{% block content %}
    {% if latest_quizzes_list %}
    <h1><span class="glyphicon glyphicon-fire" style="color:#EC4E20"></span> Latest quizzes</h1>
        <ul>
            {% for quiz in latest_quizzes_list %}
                <li>
                    <a href="{% url 'quiz:quiz_detail' subject_id=quiz.subject_id pk=quiz.id %}">
                    {{ quiz.quiz_name }}
                    </a> - {{ quiz.pub_date }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No quizzes are available.</p>
    {% endif %}
{% endblock %}
</body>
</html>

quiz/templates/quiz/profile.html
{% extends "base_generic.html" %}
{% block title %}<title>{{ profile_user.get_username }} | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h1><span class="glyphicon glyphicon-user"></span> {{ profile_user.get_username }} </h1>
    {% if user.is_authenticated and user.id == profile_user.id or user.is_staff %}
        {% if has_results %}
            <h2>Latest results</h2>
            <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr class="header">
                    <th width="35%">Quiz</th>
                    <th width="25%">Score</th>
                    <th width="40%">Date</th>
                </tr>
                </thead>
                {% for line in latest_user_results %}
                <tr>
                    <td>{{ line.quiz }}</td>
                    <td>{{ line.calc_score_percent }}</td>
                    <td>{{ line.date_taken }}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
            <h2>Best attempts</h2>
            <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr class="header">
                    <th width="35%">Quiz</th>
                    <th width="25%">Score</th>
                    <th width="40%">Date</th>
                </tr>
                </thead>
                {% for line in best_user_results %}
                <tr>
                    <td>{{ line.quiz }}</td>
                    <td>{{ line.calc_score_percent }}</td>
                    <td>{{ line.date_taken }}</td>
                </tr>
                {% endfor %}
            </table>
            </div>
            <hr>
            <a href="{% url 'quiz:all_user_results' user_id=profile_user.id %}">Show all results</a>
        {% else %}
            <p>No results to show yet!</p>
        {% endif %}
    {% else %}
        <p>you can't see this user's info</p>
    {% endif %}
{% endblock %}

quiz/templates/quiz/quiz_created.html
{% extends "base_generic.html" %}
{% block title %}<title>Quiz created | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h2>Quiz {{ quiz_name }} successfully created!</h2>
    <p><a href="{% url 'quiz:all_quizzes' %}">Go back to all quizzes</a></p>
{% endblock %}

quiz/templates/quiz/results.html
{% extends "base_generic.html" %}
{% block title %}<title> Results | MyPyQuiz</title>{% endblock %}
{% block content %}
    <div class="results_content">
        <h1> Results</h1>
        <div class="results-filter">
        <label for="subj_select">Subjects:</label>
            <select id="subj_select" onchange="getTableData(this.id)">
                <option selected value> All </option>
                {% for subj in all_subjects %}
                    <option value="{{ subj.id }}">{{ subj.subj_name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="results-filter">
        <label for="quiz_select">Quizzes:</label>
            <select id="quiz_select" onchange="getTableData(this.id)">
                <option selected value> All </option>
                {% for quiz in all_quizzes %}
                    <option value="{{ quiz.id }}">{{ quiz.quiz_name }}</option>
                {% endfor %}
            </select>        
        </div>
        <div class="results-filter">
        <label for="user_select">Users:</label>
            <select id="user_select" onchange="getTableData(this.id)">
                <option selected value> All </option>
                {% for cur_user in all_users %}
                    <option value="{{ cur_user.id }}">{{ cur_user.get_username }}</option>
                {% endfor %}
            </select>        
        </div>
        <button type="button" id="clear_filters" class="btn btn-primary" onclick="getTableData(this.id)">Clear filter</button>
        {% if results_set %}
            <div class="table-responsive">
                <table class="table table-striped" id="allUserResultsTable">
                    <thead>
                        <tr class="header">
                            <th width="20%">User</th>
                            <th width="25%">Quiz</th>
                            <th width="15%">Score</th>
                            <th width="15%">% score</th>
                            <th width="25%">Date</th>
                        </tr>
                    </thead>
                    <tbody id="result_table">
                    {% for line in results_set %}
                    <tr>
                        <td>{{ line.user }}</td>
                        <td>{{ line.quiz }}</td>
                        {% if user.is_staff or user.userrole.isSupervisor %}
                        <td><a href="{% url 'quiz:result_details' result_id=line.id %}">{{ line.score }}</a></td>
                        {% else %}
                        <td>{{ line.score }}</td>
                        {% endif %}
                        <td>{{ line.calc_score_percent }}</td>
                        <td>{{ line.date_taken|date:"d M Y, H:i" }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>    
        {% else %}
            <p>No results to show yet!</p>
        {% endif %}
    </div>
{% endblock %}
{% block script %}
<script>
function getTableData(filterId) {
    var filter = document.getElementById(filterId);
    if (filter.id != 'clear_filters') {
        var selectedOption = filter.options[filter.selectedIndex].value;
        var url = '';
        switch (filter.id) {
            case 'subj_select':
                url = selectedOption ?
                      "{% url 'quiz:ajax_results_by_subj' subject_id=100500 %}".replace (100500, selectedOption) :
                      "{% url 'quiz:ajax_all_results' %}";
                break;
            case 'quiz_select':
                url = selectedOption ?
                      "{% url 'quiz:ajax_results_by_quiz' quiz_id=100500 %}".replace (100500, selectedOption) :
                      "{% url 'quiz:ajax_all_results' %}";
                break;
            case 'user_select':
                url = selectedOption ? 
                      "{% url 'quiz:ajax_results_by_user' user_id=100500 %}".replace (100500, selectedOption) :
                      "{% url 'quiz:ajax_all_results' %}";
                break;
            default:
                break;
        }
        var otherFilters = $('.results-filter select[id!='+filterId+']');
        for (var i=0; i<otherFilters.length; i++) {
            var otherFilter = otherFilters[i];
            otherFilter.selectedIndex = 0;
        }
        $( "#result_table" ).load( url );
    }
    else {
        var otherFilters = $('.results-filter select');
        for (var i=0; i<otherFilters.length; i++) {
            var otherFilter = otherFilters[i];
            otherFilter.selectedIndex = 0;
        }
        $( "#result_table" ).load("{% url 'quiz:ajax_all_results' %}");
    }
}
var selectBox = document.getElementsByName("items-on-page")[0];
</script>
{% endblock %}

quiz/templates/quiz/signup.html
{% extends "base_generic.html" %}
{% block title %}<title>Sign Up | MyPyQuiz</title>{% endblock %}
{% block content %}
    <div id="signup" class="text-center">
	    <h2>Sign up</h2>
	    <div class="signup-form">
		    <form method="post">
		        {% csrf_token %}
		            {{ form.as_p }}
		        <button type="submit" class="btn btn-primary btn-lg">
                    Sign up
                </button>
		    </form>
		</div>
    </div>
{% endblock %}

quiz/templates/quiz/subject_created.html
{% extends "base_generic.html" %}
{% block title %}<title>Subject created | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h2>Subject {{ subj_name }} successfully created!</h2>
    <p><a href="{% url 'quiz:all_subjects' %}">Go back to all subjects</a></p>
{% endblock %}

quiz/templates/quiz/subject_quizzes.html
{% extends "base_generic.html" %}
{% block title %}<title>Quizzes by subject | MyPyQuiz</title>{% endblock %}
{% block content %}
    <h1> All quizzes on {{ subject }}</h1>
    {% if quizzes %}
        <div class="table-responsive" id="subj-quizzes-table">
        <table class="table table-striped">
            {% for quiz in quizzes %}
                <tr>
                    <td>
                        <a href="{% url 'quiz:quiz_detail' subject_id=quiz.subject_id pk=quiz.id %}">
                            {{ quiz.quiz_name }}
                        </a>
                    </td>
                    <td class="start-quiz">
                        <a href="{% url 'quiz:start_quiz' subject_id=quiz.subject_id pk=quiz.id %}" title="Start quiz">
                            <span class="glyphicon glyphicon-check"></span>
                        </a>
                    </td>
                    {% if user.is_authenticated and user.is_staff %}
                    <td class="delete-item">
                        <a href="{% url 'quiz:delete_quiz' quiz_id=quiz.id %}" title="Delete quiz">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                    </td>
                    {% endif %}
                </tr>        
            {% endfor %}
        </table>
        </div>
    {% else %}
        <p>No quizzes available.</p>
    {% endif %}
{% endblock %}